name: Build By Script And Push
on:
    workflow_dispatch:
        inputs:
            context:
                description: "构建根目录"
                required: true
                default: ""
            script:
                description: "脚本路径"
                required: true
                default: "build.sh"

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker Login
              uses: docker/login-action@v3.2.0
              with:
                  registry: registry.cn-beijing.aliyuncs.com
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}

            - name: Run Script
              shell: bash
              run: |
                  cd ${{ github.event.inputs.context }}
                  ./${{ github.event.inputs.script }}
